language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - DB=mysql TYPO3_BRANCH=TYPO3_6-2
    - DB=mysql TYPO3_BRANCH=TYPO3_7-6
    - DB=mysql TYPO3_BRANCH=master
  global:
    secure: INo+FZa/Z2hTw6UwwMh0qjKllgIlqSz8S7S76HGR15L4sqnmG22spT4IwXjavV2jfR/Glo6PxR5dz9Bn9Br03dh72MThLKqBAI9pJR+Ig3SNcvOGCm/8h4hrKUKJDkge+GQEzL4HuXO0OenEIPXCSlNFlBxQN824TMJFQgvGHnA=

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=mysql TYPO3_BRANCH=TYPO3_7-6
  exclude:
    - php: 5.4
      env: DB=mysql TYPO3_BRANCH=TYPO3_7-6
    - php: 5.4
      env: DB=mysql TYPO3_BRANCH=master
    - php: 5.5
      env: DB=mysql TYPO3_BRANCH=master
    - php: 5.6
      env: DB=mysql TYPO3_BRANCH=master
    - php: 7.0
      env: DB=mysql TYPO3_BRANCH=TYPO3_6-2

sudo: false

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - derhansen@gmail.com

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv sf_yubikey typo3conf/ext/

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3conf/ext/sf_yubikey/Tests/Build/UnitTests.xml
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
        if ! find typo3conf/ext/sf_yubikey -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
            grep -v \"No syntax errors detected in\" /tmp/errors;
            exit 99;
        fi
    "