language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.0
      env: TYPO3_VERSION=^8

sudo: false

env:
  global:
    secure: INo+FZa/Z2hTw6UwwMh0qjKllgIlqSz8S7S76HGR15L4sqnmG22spT4IwXjavV2jfR/Glo6PxR5dz9Bn9Br03dh72MThLKqBAI9pJR+Ig3SNcvOGCm/8h4hrKUKJDkge+GQEzL4HuXO0OenEIPXCSlNFlBxQN824TMJFQgvGHnA=

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - derhansen@gmail.com

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - if [ -d .Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build ]; then export TYPO3_BUILD_DIR=".Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build"; else export TYPO3_BUILD_DIR=".Build/vendor/typo3/cms/typo3/sysext/core/Build"; fi

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c $TYPO3_BUILD_DIR/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;