name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - { php: 8.1, coverage: 0}
          - { php: 8.2, coverage: 0}

    env: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install composer dependencies
        run: |
          composer install --no-progress

      - name: Unit Tests
        run: |
          .Build/bin/phpunit
